const audioActionTypes = {
  AUDIO_TOGGLE_SELECT: 'AUDIO_TOGGLE_SELECT',
  AUDIO_TOGGLE_SELECT_ALL: 'AUDIO_TOGGLE_SELECT_ALL',
  AUDIO_UPLOAD_LIST_PENDING: 'AUDIO_UPLOAD_LIST_PENDING',
  AUDIO_UPLOAD_LIST_SUCCESS: 'AUDIO_UPLOAD_LIST_SUCCESS'
};

export default audioActionTypes;