const audioActionTypes = {
  GET: 'AUDIO_GET',
  DOWNLOAD_START: 'DOWNLOAD_START',
  DOWNLOAD_PROGRESS: 'DOWNLOAD_PROGRESS',
  DOWNLOAD_COMPLETE: 'DOWNLOAD_COMPLETE',
  FILTER_CHANGE: 'FILTER_CHANGE',

  FAILURE: 'AUDIO_FAILURE'
};

export default audioActionTypes;